// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/Layouts/ColorMap.tsx";
import * as $$$1 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$2 from "./loaders/List/Sections.tsx";
import * as $$$3 from "./loaders/newsletter.ts";
import * as $$$4 from "./loaders/proxy.ts";
import * as $$$$$$0 from "./sections/Category/BannerCategoryGrid.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryMenu.tsx";
import * as $$$$$$3 from "./sections/Content/BannerGrid.tsx";
import * as $$$$$$4 from "./sections/Content/Stores.tsx";
import * as $$$$$$5 from "./sections/Content/TextSEO.tsx";
import * as $$$$$$6 from "./sections/Content/VideoAndText.tsx";
import * as $$$$$$7 from "./sections/DataLayer/Home.tsx";
import * as $$$$$$8 from "./sections/Footer/Footer.tsx";
import * as $$$$$$9 from "./sections/Gallery.tsx";
import * as $$$$$$10 from "./sections/Header/Header.tsx";
import * as $$$$$$11 from "./sections/Images/Carousel.tsx";
import * as $$$$$$12 from "./sections/Institutional/AccordionsContent.tsx";
import * as $$$$$$13 from "./sections/Institutional/AsideMenu.tsx";
import * as $$$$$$14 from "./sections/Institutional/CardsContent.tsx";
import * as $$$$$$15 from "./sections/Institutional/ContactForm.tsx";
import * as $$$$$$16 from "./sections/Institutional/FeaturedStore.tsx";
import * as $$$$$$17 from "./sections/Institutional/InstitutionalPage.tsx";
import * as $$$$$$18 from "./sections/Institutional/StoresList.tsx";
import * as $$$$$$19 from "./sections/Institutional/TextContent.tsx";
import * as $$$$$$20 from "./sections/Layout/Container.tsx";
import * as $$$$$$21 from "./sections/Layout/Flex.tsx";
import * as $$$$$$22 from "./sections/Layout/Grid.tsx";
import * as $$$$$$23 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$24 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$25 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$26 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$27 from "./sections/Product/FeaturedGallery.tsx";
import * as $$$$$$28 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$29 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$30 from "./sections/Product/NotFound.tsx";
import * as $$$$$$31 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$32 from "./sections/Product/PhotoGallery.tsx";
import * as $$$$$$33 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$34 from "./sections/Product/ProductGallery.tsx";
import * as $$$$$$35 from "./sections/Product/ProductRelatedShelf.tsx";
import * as $$$$$$36 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$37 from "./sections/Product/ProductShelfByPage.tsx";
import * as $$$$$$38 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$39 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$40 from "./sections/Product/SearchResultMenu.tsx";
import * as $$$$$$41 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$42 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$43 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$44 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/Layouts/ColorMap.tsx": $$$0,
    "site/loaders/Layouts/ProductCard.tsx": $$$1,
    "site/loaders/List/Sections.tsx": $$$2,
    "site/loaders/newsletter.ts": $$$3,
    "site/loaders/proxy.ts": $$$4,
  },
  "sections": {
    "site/sections/Category/BannerCategoryGrid.tsx": $$$$$$0,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$1,
    "site/sections/Category/CategoryMenu.tsx": $$$$$$2,
    "site/sections/Content/BannerGrid.tsx": $$$$$$3,
    "site/sections/Content/Stores.tsx": $$$$$$4,
    "site/sections/Content/TextSEO.tsx": $$$$$$5,
    "site/sections/Content/VideoAndText.tsx": $$$$$$6,
    "site/sections/DataLayer/Home.tsx": $$$$$$7,
    "site/sections/Footer/Footer.tsx": $$$$$$8,
    "site/sections/Gallery.tsx": $$$$$$9,
    "site/sections/Header/Header.tsx": $$$$$$10,
    "site/sections/Images/Carousel.tsx": $$$$$$11,
    "site/sections/Institutional/AccordionsContent.tsx":
      $$$$$$12,
    "site/sections/Institutional/AsideMenu.tsx": $$$$$$13,
    "site/sections/Institutional/CardsContent.tsx": $$$$$$14,
    "site/sections/Institutional/ContactForm.tsx": $$$$$$15,
    "site/sections/Institutional/FeaturedStore.tsx":
      $$$$$$16,
    "site/sections/Institutional/InstitutionalPage.tsx":
      $$$$$$17,
    "site/sections/Institutional/StoresList.tsx": $$$$$$18,
    "site/sections/Institutional/TextContent.tsx": $$$$$$19,
    "site/sections/Layout/Container.tsx": $$$$$$20,
    "site/sections/Layout/Flex.tsx": $$$$$$21,
    "site/sections/Layout/Grid.tsx": $$$$$$22,
    "site/sections/Layout/GridItem.tsx": $$$$$$23,
    "site/sections/Miscellaneous/CampaignTimer.tsx":
      $$$$$$24,
    "site/sections/Miscellaneous/CookieConsent.tsx":
      $$$$$$25,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$26,
    "site/sections/Product/FeaturedGallery.tsx": $$$$$$27,
    "site/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$28,
    "site/sections/Product/ImageGallerySlider.tsx": $$$$$$29,
    "site/sections/Product/NotFound.tsx": $$$$$$30,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$31,
    "site/sections/Product/PhotoGallery.tsx": $$$$$$32,
    "site/sections/Product/ProductDetails.tsx": $$$$$$33,
    "site/sections/Product/ProductGallery.tsx": $$$$$$34,
    "site/sections/Product/ProductRelatedShelf.tsx":
      $$$$$$35,
    "site/sections/Product/ProductShelf.tsx": $$$$$$36,
    "site/sections/Product/ProductShelfByPage.tsx": $$$$$$37,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$38,
    "site/sections/Product/SearchResult.tsx": $$$$$$39,
    "site/sections/Product/SearchResultMenu.tsx": $$$$$$40,
    "site/sections/Product/Wishlist.tsx": $$$$$$41,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$42,
    "site/sections/Social/WhatsApp.tsx": $$$$$$43,
    "site/sections/Theme/Theme.tsx": $$$$$$44,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
